// Shim → re-export from PostgreSQL DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings,
  getProviderConnections, countProviderConnections, getProviderConnectionById, getProviderSummaryStats,
  setProviderConnectionsActive, setConnectionsActiveByIds,
  getProxyPoolBoundCounts, countProxyPoolBoundConnections,
  countProxyGroupBoundConnections,
  getUnavailableOrLockedConnections,
  getClientUsageConnections, getClientUsageMeta,
  getAvailableAccountsForRouting, touchAccountLastUsed,
  setModelCooldown, clearModelCooldown,
  lockAccountToModel, unlockAccountModel,
  createProviderConnection, updateProviderConnection,
  getBatchProviderQuotas, getUsageSnapshotByConnectionId,
  deleteProviderConnection, deleteProviderConnectionsByIds, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  bulkResetProviderConnectionsStatus, autoRecoverExpiredExhaustedConnections, bulkUpdateProviderProxy,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool, deleteDisabledProxyPools,
  invalidateProxyPoolCache,
  getProxyGroups, getProxyGroupById, getProxyGroupByName,
  createProxyGroup, updateProxyGroup, deleteProxyGroup,
  lockProxyPoolForScope,
  invalidateProxyGroupCache,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  exportDb, importDb, pruneUsageHistory,
} from "@/lib/db/index.js";
