// Re-export barrel — all public API from sub-modules
export {
  DB_BACKUP_FORMAT,
  DB_BACKUP_SCHEMA_VERSION,
  normalizeChatRuntimeSettings,
  getDefaultChatRuntimeSettings,
  normalizeMorphSettings,
  mergeSettingsWithDefaults,
} from "./localDb/normalize";

export {
  getConnectionEffectiveStatus,
  getDb,
  migrateDbShape,
  prepareLocalDbForExternalRestore,
  reloadLocalDbAfterExternalRestore,
} from "./localDb/core";

export {
  getProviderConnections,
  getProviderConnectionById,
  createProviderConnection,
  updateProviderConnection,
  atomicUpdateProviderConnection,
  deleteProviderConnection,
  deleteProviderConnectionsByProvider,
  reorderProviderConnections,
  cleanupProviderConnections,
} from "./localDb/providers";

export {
  getCombos,
  getComboById,
  getComboByName,
  createCombo,
  updateCombo,
  renameComboWithDependents,
  reorderCombos,
  deleteCombo,
  getModelComboMappings,
  getModelComboMappingById,
  createModelComboMapping,
  updateModelComboMapping,
  deleteModelComboMapping,
  globToRegex,
  resolveComboForModel,
} from "./localDb/combos";

export {
  getProviderNodes,
  getProviderNodeById,
  createProviderNode,
  updateProviderNode,
  deleteProviderNode,
  getProxyPools,
  getProxyPoolById,
  createProxyPool,
  updateProxyPool,
  deleteProxyPool,
  getProxyGroups,
  getProxyGroupById,
  createProxyGroup,
  updateProxyGroup,
  deleteProxyGroup,
  getModelAliases,
  setModelAlias,
  deleteModelAlias,
  getCustomModels,
  getAllSyncedAvailableModels,
  getSyncedAvailableModelsForConnection,
  replaceSyncedAvailableModelsForConnection,
  deleteSyncedAvailableModelsForConnection,
  getDisabledModels,
  disableModels,
  enableModels,
  addCustomModel,
  deleteCustomModel,
  getCustomSkills,
  createCustomSkill,
  updateCustomSkill,
  deleteCustomSkill,
  duplicateCustomSkill,
  getMitmAlias,
  setMitmAliasAll,
  setMitmAlias,
  deleteMitmAlias,
  getApiKeys,
  createApiKey,
  deleteApiKey,
  getApiKeyById,
  updateApiKey,
  validateApiKey,
  getSettings,
  atomicUpdateSettings,
  updateSettings,
  exportDb,
  importDb,
  getPricing,
  getPricingForModel,
  updatePricing,
  resetPricing,
  resetAllPricing,
  getOpenCodeSync,
  getOpenCodePreferences,
  updateOpenCodePreferences,
  listOpenCodeTokens,
  replaceOpenCodeTokens,
  mutateOpenCodeTokens,
  touchOpenCodeTokenLastUsedAt,
} from "./localDb/misc";

export {
  getProviderConnectionStatusSummary,
} from "./providerConnectionSummary";
