export default {
  id: "cloudflare-ai",
  priority: 60,
  hasFree: true,
  alias: "cloudflare-ai",
  aliases: [
    "cf",
  ],
  uiAlias: "cf",
  display: {
    name: "Cloudflare",
    icon: "cloud",
    color: "#F38020",
    textIcon: "CF",
    website: "https://developers.cloudflare.com/workers-ai/",
    notice: {
      text: "Workers AI free tier. Requires a Cloudflare API token and Account ID.",
      apiKeyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  hasProviderSpecificData: true,
  transport: {
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1/chat/completions",
    thinkingFormat: "openai",
  },
  models: [
    // ── Text Generation (free tier, probe-verified 200) ──
    { id: "@cf/aisingapore/gemma-sea-lion-v4-27b-it", name: "Gemma Sea Lion v4 27B IT" },
    { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B" },
    { id: "@cf/google/gemma-2b-it-lora", name: "Gemma 2B IT LoRA" },
    { id: "@cf/google/gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B IT" },
    { id: "@cf/google/gemma-7b-it-lora", name: "Gemma 7B IT LoRA" },
    { id: "@cf/ibm-granite/granite-4.0-h-micro", name: "Granite 4.0 H Micro" },
    { id: "@cf/meta-llama/llama-2-7b-chat-hf-lora", name: "Llama 2 7B Chat HF LoRA" },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8", name: "Llama 3.1 8B Instruct FP8" },
    { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct" },
    { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct" },
    { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B 16E Instruct" },
    { id: "@cf/meta/llama-guard-3-8b", name: "Llama Guard 3 8B" },
    { id: "@cf/mistral/mistral-7b-instruct-v0.2-lora", name: "Mistral 7B Instruct v0.2 LoRA" },
    { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct" },
    { id: "@cf/moondream/moondream3.1-9B-A2B", name: "Moondream 3.1 9B A2B" },
    { id: "@cf/nvidia/nemotron-3-120b-a12b", name: "Nemotron 3 120B A12B" },
    { id: "@cf/openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "@cf/openai/gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32B Instruct" },
    { id: "@cf/qwen/qwen3-30b-a3b-fp8", name: "Qwen3 30B A3B FP8" },
    { id: "@cf/qwen/qwen3.8-27b", name: "Qwen3.8 27B" },
    { id: "@cf/qwen/qwq-32b", name: "QwQ 32B" },
    { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash" },
    // ── Image (free tier) ──
    { id: "@cf/black-forest-labs/flux-2-klein-9b", name: "FLUX.2 Klein 9B", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-2-klein-4b", name: "FLUX.2 Klein 4B", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-2-dev", name: "FLUX.2 Dev", params: ["size"], kind: "image" },
    { id: "@cf/leonardo/lucid-origin", name: "Lucid Origin", params: ["size"], kind: "image" },
    { id: "@cf/leonardo/phoenix-1.0", name: "Phoenix 1.0", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-1-schnell", name: "FLUX.1 Schnell", kind: "image" },
    { id: "@cf/bytedance/stable-diffusion-xl-lightning", name: "SDXL Lightning", params: ["size"], kind: "image" },
    { id: "@cf/lykon/dreamshaper-8-lcm", name: "DreamShaper 8 LCM", params: ["size"], kind: "image" },
    { id: "@cf/runwayml/stable-diffusion-v1-5-inpainting", name: "Stable Diffusion v1.5 Inpainting", params: ["size"], capabilities: ["edit","mask"], kind: "image" },
    { id: "@cf/stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", params: ["size"], kind: "image" },
    // ── Embedding (free tier) ──
    { id: "@cf/baai/bge-large-en-v1.5", name: "BGE Large EN v1.5", dimensions: 1024, kind: "embedding" },
    { id: "@cf/baai/bge-base-en-v1.5", name: "BGE Base EN v1.5", dimensions: 768, kind: "embedding" },
    { id: "@cf/baai/bge-small-en-v1.5", name: "BGE Small EN v1.5", dimensions: 384, kind: "embedding" },
    { id: "@cf/baai/bge-m3", name: "BGE-M3", dimensions: 1024, kind: "embedding" },
    { id: "@cf/qwen/qwen3-embedding-0.6b", name: "Qwen3 Embedding 0.6B", dimensions: 1024, kind: "embedding" },
    { id: "@cf/google/embeddinggemma-300m", name: "EmbeddingGemma 300M", dimensions: 768, kind: "embedding" },
    { id: "@cf/pfnet/plamo-embedding-1b", name: "PLaMo Embedding 1B", dimensions: 1024, kind: "embedding" },
  ],
  serviceKinds: ["llm","image","embedding"],
  imageConfig: { baseUrl: "https://api.cloudflare.com/client/v4/accounts" },
};
