export default {
  id: "kilocode-free",
  priority: 45,
  hasFree: true,
  alias: "kcf",
  aliases: [
    "kilocode-free",
    "kilo-free",
    "kf",
  ],
  uiAlias: "kcf",
  display: {
    name: "Kilo Code Free",
    icon: "code",
    color: "#FF6B35",
    textIcon: "KF",
    website: "https://kilo.ai",
    notice: {
      text: "Free AI models powered by Kilo AI Gateway. No account or API key required (IP rate-limited to 200 req/hr).",
    },
  },
  category: "free",
  noAuth: true,
  transport: {
    baseUrl: "https://api.kilo.ai/api/gateway/chat/completions",
    noAuth: true,
  },
  models: [
    { id: "kilo-auto/free", name: "Auto Free", contextLength: 256000, maxTokens: 10000 },
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra 550B (Free)", contextLength: 1000000, maxTokens: 65536, reasoning: true },
    { id: "nvidia/nemotron-3.5-lightning:free", name: "Nemotron 3.5 Lightning (Free)", contextLength: 1000000, maxTokens: 65536, reasoning: true },
    { id: "thinkingmachines/inkling-small:free", name: "Inkling Small (Free)", contextLength: 1048576, maxTokens: 262144, vision: true, reasoning: true },
    { id: "dots-studio/dots-3-note-preview:free", name: "Dots 3 Note Preview (Free)", contextLength: 512000, maxTokens: 460800, vision: true, reasoning: true },
    { id: "stepfun/step-3.7-flash:free", name: "StepFun Step 3.7 Flash (Free)", contextLength: 262144, maxTokens: 262144, vision: true, reasoning: true },
    { id: "qwen/qwen3.8-27b:free", name: "Qwen 3.8 27B (Free)", contextLength: 262144, maxTokens: 235929, vision: true, reasoning: true },
    { id: "nex-agi/nex-n2.5-pro:free", name: "Nex N2.5 Pro (Free)", contextLength: 262144, maxTokens: 235929, vision: true, reasoning: true },
    { id: "nex-agi/nex-n2.5-mini:free", name: "Nex N2.5 Mini (Free)", contextLength: 262144, maxTokens: 235929, vision: true, reasoning: true },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super 120B (Free)", contextLength: 262144, maxTokens: 235929, reasoning: true },
    { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1 (Free)", contextLength: 262144, maxTokens: 32768, reasoning: true },
    { id: "poolside/laguna-xs-2.1:free", name: "Laguna XS 2.1 (Free)", contextLength: 262144, maxTokens: 32768, reasoning: true },
    { id: "inclusionai/ling-3.0-flash-vl:free", name: "Ling 3.0 Flash VL (Free)", contextLength: 262144, maxTokens: 32768, vision: true, reasoning: true },
    { id: "inclusionai/ling-3.0-flash-sante:free", name: "Ling 3.0 Flash Santé (Free)", contextLength: 262144, maxTokens: 32768, reasoning: true },
    { id: "inclusionai/ling-3.0-flash-fin:free", name: "Ling 3.0 Flash Fin (Free)", contextLength: 262144, maxTokens: 32768, reasoning: true },
    { id: "cohere/north-mini-code:free", name: "North Mini Code (Free)", contextLength: 256000, maxTokens: 64000, reasoning: true },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "Nemotron 3 Nano Omni (Free)", contextLength: 256000, maxTokens: 65536, vision: true, reasoning: true },
    { id: "openrouter/free", name: "OpenRouter Free (Free)", contextLength: 200000, vision: true, reasoning: true },
    { id: "nvidia/nemotron-3.5-content-safety:free", name: "Nemotron 3.5 Content Safety (Free)", contextLength: 128000, maxTokens: 8192, vision: true, reasoning: true },
    { id: "liquid/lfm-2.5-2.6b:free", name: "LiquidAI LFM 2.5 2.6B (Free)", contextLength: 65536, maxTokens: 8192, reasoning: true },
    { id: "z-ai/glm-5.2:free", name: "GLM 5.2 (Free)", contextLength: 32768, maxTokens: 29491, reasoning: true },
  ],
  modelsFetcher: { url: "https://api.kilo.ai/api/gateway/models", type: "kilocode-free" },
  passthroughModels: true,
};
