export default {
  id: "kiro",
  priority: 10,
  alias: "kr",
  uiAlias: "kr",
  display: {
    name: "Kiro AI",
    icon: "psychology_alt",
    color: "#FF6B35",
    website: "https://kiro.dev",
    notice: {
      signupUrl: "https://kiro.dev",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  category: "free",
  transport: {
    baseUrl: "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
    baseUrls: [
      "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
      "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
      "https://q.us-east-1.amazonaws.com/generateAssistantResponse",
    ],
    format: "kiro",
    retry: {
      "429": 0,
    },
    headers: {
      "Content-Type": "application/json",
      Accept: "application/vnd.amazon.eventstream",
      "User-Agent": "AWS-SDK-JS/3.0.0 kiro-ide/1.0.0",
      "X-Amz-User-Agent": "aws-sdk-js/3.0.0 kiro-ide/1.0.0",
    },
    tokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authUrl: "https://prod.us-east-1.auth.desktop.kiro.dev",
    usage: {
      cwHost: "https://codewhisperer.us-east-1.amazonaws.com",
      qHost: "https://q.us-east-1.amazonaws.com",
      limitsPath: "/getUsageLimits",
    },
  },
  models: [
    // Live catalog verified 2026-10-02 via Kiro ListAvailableModels against
    // /app/api/providers/[id]/models on 2 routable accounts, then confirmed by
    // direct probes (HTTP 400 "Invalid model. Please select a different model"
    // on every account for every id removed below).
    // Each upstream id expands into plain / -thinking / -agentic / -thinking-agentic
    // variants; `auto` has no agentic form (Kiro picks the model server-side).
    { id: "auto", name: "Kiro Auto", contextLength: 1000000 },
    { id: "auto-thinking", name: "Kiro Auto (Thinking)", contextLength: 1000000 },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", contextLength: 200000 },
    { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 (Thinking)", contextLength: 200000 },
    { id: "claude-sonnet-4.5-agentic", name: "Claude Sonnet 4.5 (Agentic)", contextLength: 200000 },
    { id: "claude-sonnet-4.5-thinking-agentic", name: "Claude Sonnet 4.5 (Thinking + Agentic)", contextLength: 200000 },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4", contextLength: 200000 },
    { id: "claude-sonnet-4-thinking", name: "Claude Sonnet 4 (Thinking)", contextLength: 200000 },
    { id: "claude-sonnet-4-agentic", name: "Claude Sonnet 4 (Agentic)", contextLength: 200000 },
    { id: "claude-sonnet-4-thinking-agentic", name: "Claude Sonnet 4 (Thinking + Agentic)", contextLength: 200000 },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", contextLength: 200000 },
    { id: "claude-haiku-4.5-thinking", name: "Claude Haiku 4.5 (Thinking)", contextLength: 200000 },
    { id: "claude-haiku-4.5-agentic", name: "Claude Haiku 4.5 (Agentic)", contextLength: 200000 },
    { id: "claude-haiku-4.5-thinking-agentic", name: "Claude Haiku 4.5 (Thinking + Agentic)", contextLength: 200000 },
    { id: "deepseek-3.2", name: "DeepSeek 3.2", strip: ["image","audio"], contextLength: 200000 },
    { id: "deepseek-3.2-thinking", name: "DeepSeek 3.2 (Thinking)", strip: ["image","audio"], contextLength: 200000 },
    { id: "deepseek-3.2-agentic", name: "DeepSeek 3.2 (Agentic)", strip: ["image","audio"], contextLength: 200000 },
    { id: "deepseek-3.2-thinking-agentic", name: "DeepSeek 3.2 (Thinking + Agentic)", strip: ["image","audio"], contextLength: 200000 },
    { id: "minimax-m2.5", name: "MiniMax M2.5", contextLength: 200000 },
    { id: "minimax-m2.5-thinking", name: "MiniMax M2.5 (Thinking)", contextLength: 200000 },
    { id: "minimax-m2.5-agentic", name: "MiniMax M2.5 (Agentic)", contextLength: 200000 },
    { id: "minimax-m2.5-thinking-agentic", name: "MiniMax M2.5 (Thinking + Agentic)", contextLength: 200000 },
    { id: "minimax-m2.1", name: "MiniMax M2.1", contextLength: 200000 },
    { id: "minimax-m2.1-thinking", name: "MiniMax M2.1 (Thinking)", contextLength: 200000 },
    { id: "minimax-m2.1-agentic", name: "MiniMax M2.1 (Agentic)", contextLength: 200000 },
    { id: "minimax-m2.1-thinking-agentic", name: "MiniMax M2.1 (Thinking + Agentic)", contextLength: 200000 },
    { id: "glm-5", name: "GLM 5", contextLength: 200000 },
    { id: "glm-5-thinking", name: "GLM 5 (Thinking)", contextLength: 200000 },
    { id: "glm-5-agentic", name: "GLM 5 (Agentic)", contextLength: 200000 },
    { id: "glm-5-thinking-agentic", name: "GLM 5 (Thinking + Agentic)", contextLength: 200000 },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next", strip: ["image","audio"], contextLength: 200000 },
    { id: "qwen3-coder-next-thinking", name: "Qwen3 Coder Next (Thinking)", strip: ["image","audio"], contextLength: 200000 },
    { id: "qwen3-coder-next-agentic", name: "Qwen3 Coder Next (Agentic)", strip: ["image","audio"], contextLength: 200000 },
    { id: "qwen3-coder-next-thinking-agentic", name: "Qwen3 Coder Next (Thinking + Agentic)", strip: ["image","audio"], contextLength: 200000 },
  ],
  passthroughModels: true,
  oauth: {
    ssoOidcEndpoint: "https://oidc.us-east-1.amazonaws.com",
    registerClientUrl: "https://oidc.us-east-1.amazonaws.com/client/register",
    deviceAuthUrl: "https://oidc.us-east-1.amazonaws.com/device_authorization",
    tokenUrl: "https://oidc.us-east-1.amazonaws.com/token",
    startUrl: "https://view.awsapps.com/start",
    clientName: "kiro-oauth-client",
    clientType: "public",
    scopes: [
      "codewhisperer:completions",
      "codewhisperer:analysis",
      "codewhisperer:conversations",
    ],
    grantTypes: [
      "urn:ietf:params:oauth:grant-type:device_code",
      "refresh_token",
    ],
    issuerUrl: "https://identitycenter.amazonaws.com/ssoins-722374e8c3c8e6c6",
    socialAuthEndpoint: "https://prod.us-east-1.auth.desktop.kiro.dev",
    socialLoginUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/login",
    socialTokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/oauth/token",
    socialRefreshUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authMethods: [
      "builder-id",
      "idc",
      "google",
      "github",
      "import",
    ],
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
