export default {
  id: "orcarouter",
  priority: 110,
  alias: "orcarouter",
  aliases: ["orca"],
  uiAlias: "orca",
  display: {
    name: "OrcaRouter",
    icon: "hub",
    color: "#0284C7",
    textIcon: "ORCA",
    website: "https://www.orcarouter.ai",
    notice: {
      text: "OpenAI-compatible adaptive routing gateway. 200+ models across frontier and open-source.",
      apiKeyUrl: "https://www.orcarouter.ai/console/api-keys",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.orcarouter.ai/v1/chat/completions",
    validateUrl: "https://api.orcarouter.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "orcarouter/auto", name: "Auto (smart routing)", upstreamModelId: "orcarouter/auto" },
    { id: "auto", name: "Auto (smart routing)", upstreamModelId: "orcarouter/auto" },
    { id: "orcarouter/free", name: "Free (free tier router)", upstreamModelId: "orcarouter/free", isFree: true },
    { id: "free", name: "Free (free tier router)", upstreamModelId: "orcarouter/free", isFree: true },
    { id: "deepseek/deepseek-v4-flash-free", name: "DeepSeek V4 Flash (Free)", upstreamModelId: "deepseek/deepseek-v4-flash-free", isFree: true },
    { id: "tencent/hy3-free", name: "Tencent HY3 (Free)", upstreamModelId: "tencent/hy3-free", isFree: true },
    { id: "z-ai/glm-5.3-flash-free", name: "GLM 5.3 Flash (Free)", upstreamModelId: "z-ai/glm-5.3-flash-free", isFree: true },
    { id: "orcarouter/fusion", name: "Fusion", upstreamModelId: "orcarouter/fusion" },
    { id: "fusion", name: "Fusion", upstreamModelId: "orcarouter/fusion" },
    { id: "orcarouter/fusion-flash", name: "Fusion Flash", upstreamModelId: "orcarouter/fusion-flash" },
    { id: "fusion-flash", name: "Fusion Flash", upstreamModelId: "orcarouter/fusion-flash" },
    { id: "orcarouter/fusion-mini", name: "Fusion Mini", upstreamModelId: "orcarouter/fusion-mini" },
    { id: "fusion-mini", name: "Fusion Mini", upstreamModelId: "orcarouter/fusion-mini" },
    { id: "openai/gpt-5.5", name: "GPT-5.5", capabilities: ["vision"] },
    { id: "gpt-5.5", name: "GPT-5.5", upstreamModelId: "openai/gpt-5.5", capabilities: ["vision"] },
    { id: "openai/gpt-6-astra", name: "GPT-6 Astra", capabilities: ["vision"] },
    { id: "gpt-6-astra", name: "GPT-6 Astra", upstreamModelId: "openai/gpt-6-astra", capabilities: ["vision"] },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", capabilities: ["vision"] },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", upstreamModelId: "google/gemini-3.8-flash", capabilities: ["vision"] },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", capabilities: ["vision"] },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", upstreamModelId: "google/gemini-3.5-flash", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", capabilities: ["vision"] },
    { id: "claude-opus-5", name: "Claude Opus 5", upstreamModelId: "anthropic/claude-opus-5", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8", capabilities: ["vision"] },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8", upstreamModelId: "anthropic/claude-opus-4.8", capabilities: ["vision"] },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6", capabilities: ["vision"] },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", upstreamModelId: "anthropic/claude-sonnet-4.6", capabilities: ["vision"] },
    { id: "grok/grok-4.3", name: "Grok 4.3", capabilities: ["vision"] },
    { id: "grok-4.3", name: "Grok 4.3", upstreamModelId: "grok/grok-4.3", capabilities: ["vision"] },
    { id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", upstreamModelId: "deepseek/deepseek-v4.1-flash" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", upstreamModelId: "deepseek/deepseek-v4-pro" },
    { id: "minimax/minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m2.7", name: "MiniMax M2.7", upstreamModelId: "minimax/minimax-m2.7" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max", upstreamModelId: "qwen/qwen3.7-max" },
    { id: "qwen/qwen3.8-max-0902", name: "Qwen3.8 Max" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max", upstreamModelId: "qwen/qwen3.8-max" },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://api.orcarouter.ai/v1/models", type: "orcarouter-free" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
