export default {
  id: "tokenharbor",
  priority: 110,
  alias: "tokenharbor",
  aliases: ["th"],
  uiAlias: "th",
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#0D9488",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: {
      text: "Unified API gateway for frontier AI models (OpenAI-compatible). Free $5 credit for new accounts.",
      apiKeyUrl: "https://tokenharbor.ai/dashboard",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
    thinkingFormat: "openai",
    forceStream: true,
  },
  models: [
    // --- Free Models ---
    { id: "deepseek-v4.1-flash:free", name: "DeepSeek V4.1 Flash (Free)", isFree: true },
    { id: "deepseek/deepseek-v4.1-flash:free", name: "DeepSeek V4.1 Flash (Free)", upstreamModelId: "deepseek-v4.1-flash:free", isFree: true },
    { id: "deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)", isFree: true },
    { id: "deepseek/deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)", upstreamModelId: "deepseek-v4-flash:free", isFree: true },
    { id: "mimo-v2.6-flash:free", name: "Xiaomi MiMo V2.6 Flash (Free)", isFree: true },
    { id: "xiaomi/mimo-v2.6-flash:free", name: "Xiaomi MiMo V2.6 Flash (Free)", upstreamModelId: "mimo-v2.6-flash:free", isFree: true },
    { id: "mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)", isFree: true },
    { id: "xiaomi/mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)", upstreamModelId: "mimo-v2.5:free", isFree: true },
    { id: "qwen3.8-flash:free", name: "Qwen3.8 Flash (Free)", isFree: true },
    { id: "qwen/qwen3.8-flash:free", name: "Qwen3.8 Flash (Free)", upstreamModelId: "qwen3.8-flash:free", isFree: true },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://tokenharbor.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
