export default {
  id: "tokenharbor",
  priority: 110,
  alias: "tokenharbor",
  aliases: ["th"],
  uiAlias: "th",
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#0D9488",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: {
      text: "Unified API gateway for frontier AI models (OpenAI-compatible). Free $5 credit for new accounts.",
      apiKeyUrl: "https://tokenharbor.ai/dashboard",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    // --- Free Models ---
    { id: "deepseek-v4.1-flash:free", name: "DeepSeek V4.1 Flash (Free)", isFree: true },
    { id: "deepseek/deepseek-v4.1-flash:free", name: "DeepSeek V4.1 Flash (Free)", upstreamModelId: "deepseek-v4.1-flash:free", isFree: true },
    { id: "deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)", isFree: true },
    { id: "deepseek/deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)", upstreamModelId: "deepseek-v4-flash:free", isFree: true },
    { id: "mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)", isFree: true },
    { id: "xiaomi/mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)", upstreamModelId: "mimo-v2.5:free", isFree: true },

    // --- Flagship Models (Bare IDs match Upstream TokenHarbor) ---
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", capabilities: ["vision"] },
    { id: "openai/gpt-5.6-sol", name: "GPT-5.6 Sol", upstreamModelId: "gpt-5.6-sol", capabilities: ["vision"] },
    { id: "gpt-6-astra", name: "GPT-6 Astra", capabilities: ["vision"] },
    { id: "openai/gpt-6-astra", name: "GPT-6 Astra", upstreamModelId: "gpt-6-astra", capabilities: ["vision"] },
    { id: "claude-opus-5", name: "Claude Opus 5", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", upstreamModelId: "claude-opus-5", capabilities: ["vision"] },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8", upstreamModelId: "claude-opus-4.8", capabilities: ["vision"] },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", capabilities: ["vision"] },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5", upstreamModelId: "claude-sonnet-5", capabilities: ["vision"] },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", capabilities: ["vision"] },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6", upstreamModelId: "claude-sonnet-4.6", capabilities: ["vision"] },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", capabilities: ["vision"] },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", upstreamModelId: "gemini-3.8-flash", capabilities: ["vision"] },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", capabilities: ["vision"] },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash", upstreamModelId: "gemini-3.7-flash", capabilities: ["vision"] },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", capabilities: ["vision"] },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", upstreamModelId: "gemini-3.5-flash", capabilities: ["vision"] },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash", upstreamModelId: "deepseek-v4-flash" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", upstreamModelId: "deepseek-v4.1-flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", upstreamModelId: "deepseek-v4-pro" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen/qwen3.8-max", name: "Qwen3.8 Max", upstreamModelId: "qwen3.8-max" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3", upstreamModelId: "kimi-k3" },
    { id: "mimo-v2.5", name: "Xiaomi MiMo V2.5" },
    { id: "xiaomi/mimo-v2.5", name: "Xiaomi MiMo V2.5", upstreamModelId: "mimo-v2.5" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "z-ai/glm-5.3-flash", name: "GLM 5.3 Flash", upstreamModelId: "glm-5.3-flash" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "x-ai/grok-4.6", name: "Grok 4.6", upstreamModelId: "grok-4.6" },
    { id: "th-orchestra", name: "TH Orchestra (Router)" },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://tokenharbor.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
