export default {
  id: "unikey",
  priority: 120,
  alias: "unikey",
  aliases: ["uk"],
  uiAlias: "uk",
  display: {
    name: "UniKey",
    icon: "key",
    color: "#2563EB",
    textIcon: "UK",
    website: "https://www.getunikey.ai",
    notice: {
      text: "Unified AI API gateway (OpenAI-compatible). Add your UniKey API key.",
      apiKeyUrl: "https://www.getunikey.ai",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://www.getunikey.ai/v1/chat/completions",
    thinkingFormat: "openai",
  },
  videoConfig: {
    baseUrl: "https://www.getunikey.ai/v1/videos",
    singleEndpoint: true,
  },
  imageConfig: { baseUrl: "https://www.getunikey.ai/v1/images/generations" },
  models: [
    { id: "claude-opus-4-8", name: "Claude Opus 4.8", kinds: ["llm", "webSearch"], capabilities: ["search", "vision"] },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", capabilities: ["vision"] },
    {
      id: "google/gemini-3.1-pro-preview",
      name: "Google Gemini 3.1 Pro Preview",
      capabilities: ["vision"],
    },
    {
      id: "google/gemini-3.1-flash-lite",
      name: "Google Gemini 3.1 Flash Lite",
      capabilities: ["vision"],
    },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6", kinds: ["llm", "webSearch"], capabilities: ["search", "vision"] },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7", kinds: ["llm", "webSearch"], capabilities: ["search", "vision"] },
    { id: "google/gemini-3.5-flash", name: "Google Gemini 3.5 Flash" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "gpt-6-astra", name: "GPT-6 Astra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", capabilities: ["vision"] },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", capabilities: ["vision"] },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "z-ai/glm-5.1", name: "GLM 5.1" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    {
      id: "bytedance-seed/seedream-5-0-pro",
      name: "Bytedance Seedream 5.0 Pro",
      type: "video",
    },
    {
      id: "bytedance/seedance-2.5",
      name: "Bytedance Seedance 2.5",
      type: "video",
    },
    {
      id: "google/gemini-3-pro-image",
      name: "Google Gemini 3 Pro Image",
      type: "image",
    },
    {
      id: "google/gemini-3.1-flash-image",
      name: "Google Gemini 3.1 Flash Image",
      type: "image",
    },
    { id: "gpt-image-2", name: "GPT Image 2", type: "image" },
    { id: "minimax/hailuo-3", name: "MiniMax Hailuo 3", type: "video" },
    {
      id: "kwaivgi/kling-v3.0-pro",
      name: "Kuaishou Kling v3.0 Pro",
      type: "video",
    },
    {
      id: "bytedance/seedance-2.0-fast",
      name: "Bytedance Seedance 2.0 Fast",
      type: "video",
    },
    {
      id: "openai/gpt-5-image-mini",
      name: "OpenAI GPT-5 Image Mini",
      type: "image",
    },
    { id: "qwen/qwen-image-3", name: "Qwen Image 3", type: "image" },
    { id: "BAAI/bge-m3", name: "BAAI BGE-M3", type: "embedding" },
  ],
  serviceKinds: ["llm", "imageToText", "embedding", "image", "video", "webSearch"],
  searchViaChat: {
    defaultModel: "claude-opus-4-8",
    endpoint: "https://www.getunikey.ai/v1/chat/completions",
    pricingUrl: "https://www.getunikey.ai",
  },
  modelsFetcher: { url: "https://www.getunikey.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
