export const ERROR_METADATA = {
 upstream: {
 label: "Upstream Provider Error",
 description: "Provider returned HTTP 5xx or server connection failed.",
 variant: "error",
 icon: "cloud_off",
 color: "text-danger",
 barColor: "bg-danger",
 },
 rate_limit: {
 label: "Rate Limit / Quota Exceeded",
 description: "HTTP 429 Too Many Requests or token quota exhausted.",
 variant: "warning",
 icon: "speed",
 color: "text-warning",
 barColor: "bg-warning",
 },
 timeout: {
 label: "Gateway / Upstream Timeout",
 description: "Upstream exceeded response deadline or gateway timed out.",
 variant: "error",
 icon: "timer_off",
 color: "text-warning",
 barColor: "bg-warning",
 },
 auth: {
 label: "Authentication / Key Error",
 description: "Invalid API key, expired token, or forbidden (401/403).",
 variant: "error",
 icon: "key_off",
 color: "text-danger",
 barColor: "bg-danger",
 },
 cancelled: {
 label: "Client Cancelled",
 description: "Client aborted request or closed connection early.",
 variant: "default",
 icon: "cancel",
 color: "text-text-muted",
 barColor: "bg-text-muted",
 },
 stream: {
 label: "Stream Parsing Failure",
 description: "Corrupted SSE chunks or malformed JSON delta stream.",
 variant: "error",
 icon: "broken_image",
 color: "text-danger",
 barColor: "bg-danger",
 },
 internal: {
 label: "Internal Gateway Error",
 description: "Internal axonrouter pipeline error or uncaught exception.",
 variant: "error",
 icon: "dns",
 color: "text-danger",
 barColor: "bg-danger",
 },
 unknown: {
 label: "Uncategorized Failure",
 description: "Non-standard error or missing status code classification.",
 variant: "default",
 icon: "help_outline",
 color: "text-text-muted",
 barColor: "bg-text-muted",
 },
};
