export { proxy } from "./dashboardGuard";

export const config = {
  matcher: [
    "/",
    "/dashboard/:path*",
    "/api/shutdown",
    "/api/version/update",
    "/api/settings/:path*",
    "/api/keys",
    "/api/keys/:path*",
    "/api/providers/:path*",
    "/api/provider-nodes/:path*",
    "/api/proxy-pools/:path*",
    "/api/credentials/:path*",
    "/api/r2/:path*",
    "/api/combos/:path*",
    "/api/model-combo-mappings/:path*",
    "/api/models/:path*",
    "/api/model-sync",
    "/api/oauth/:path*",
    "/api/opencode/:path*",
    "/api/tunnel/:path*",
    "/api/usage/:path*",
    "/api/usage-worker/:path*",
    "/api/cloud-urls/:path*",
    "/api/cli-tools/:path*",
    "/api/skills/:path*",
    "/api/translator/:path*",
    "/api/morph/:path*",
    "/api/go-router/:path*",
    "/morphllm/:path*",
  ],
};
